// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApeLDoGihYo5BHAUzBUBfHPu7usBIycQ0',
    appId: '1:626833775425:web:1c575f5f1e7882a70c5fc0',
    messagingSenderId: '626833775425',
    projectId: 'dangermap-e7371',
    authDomain: 'dangermap-e7371.firebaseapp.com',
    storageBucket: 'dangermap-e7371.appspot.com',
    measurementId: 'G-TV7G3BJ2P2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbL2v_Io-Rx2VB7buOCVbpPSymBbCo2xI',
    appId: '1:626833775425:android:3e487220e79005c30c5fc0',
    messagingSenderId: '626833775425',
    projectId: 'dangermap-e7371',
    storageBucket: 'dangermap-e7371.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYegV-4xDWVOcNhdof6R189_qpR-zj1w0',
    appId: '1:626833775425:ios:d6381a30e7b0f6140c5fc0',
    messagingSenderId: '626833775425',
    projectId: 'dangermap-e7371',
    storageBucket: 'dangermap-e7371.appspot.com',
    iosBundleId: 'com.example.dangermap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYegV-4xDWVOcNhdof6R189_qpR-zj1w0',
    appId: '1:626833775425:ios:d6381a30e7b0f6140c5fc0',
    messagingSenderId: '626833775425',
    projectId: 'dangermap-e7371',
    storageBucket: 'dangermap-e7371.appspot.com',
    iosBundleId: 'com.example.dangermap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApeLDoGihYo5BHAUzBUBfHPu7usBIycQ0',
    appId: '1:626833775425:web:74ea2b53c1e4847b0c5fc0',
    messagingSenderId: '626833775425',
    projectId: 'dangermap-e7371',
    authDomain: 'dangermap-e7371.firebaseapp.com',
    storageBucket: 'dangermap-e7371.appspot.com',
    measurementId: 'G-VM6JN8X7FD',
  );
}
